/**
 * Generates supabase/seed.sql — the whole initial dataset as plain SQL, so it
 * can be pasted into the Supabase SQL editor with no local tooling.
 *
 * Produces the same result as `npm run setup`, minus the ratings snapshot
 * (the site computes on the fly when none exists, and the first publish from
 * the admin writes one).
 *
 * Usage: npm run seed:sql
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { parseCsvText } from "../src/lib/csv";
import { ALIASES, buildIndex, matchTeam } from "../src/lib/names";
import { loadRosterCsv } from "../src/lib/roster-csv";
import { parseSchedulePdf, toGames } from "../src/lib/schedule-pdf";
import { DEFAULT_CONFIG, type Game, type Team } from "../src/lib/types";

/** Single-quote escaping — team names contain apostrophes (St. Luke's). */
const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const num = (n: number | null) => (n === null ? "NULL" : String(n));

function attachPriors(teams: Team[]): number {
  const rows = parseCsvText(
    readFileSync("data/alpreps_preseason_2026.csv", "utf8"),
  );
  const head = rows[0].map((h) => h.trim().toLowerCase());
  const iName = head.indexOf("team");
  const iRating = head.indexOf("rating");
  const index = buildIndex(teams);
  const byName = new Map(teams.map((t) => [t.name, t]));

  let matched = 0;
  for (const r of rows.slice(1)) {
    const raw = r[iName]?.trim();
    const rating = Number(r[iRating]);
    if (!raw || !Number.isFinite(rating)) continue;
    const m = matchTeam({ raw }, index);
    const team = m.name && !m.outOfState ? byName.get(m.name) : undefined;
    if (!team) continue;
    team.preseason_prior = rating;
    team.prior_source = raw;
    matched++;
  }
  return matched;
}

async function main() {
  const teams = loadRosterCsv("data/AHSAA_Class_List_2026.csv");
  const matched = attachPriors(teams);

  const pdfs = readdirSync("data")
    .filter((f) => /week[_ ]?(\d+).*\.pdf$/i.test(f))
    .map((f) => ({
      path: `data/${f}`,
      week: Number(f.match(/week[_ ]?(\d+)/i)![1]),
    }))
    .sort((a, b) => a.week - b.week);

  let games: Game[] = [];
  const notes: string[] = [];
  for (const { path, week } of pdfs) {
    const report = await parseSchedulePdf(
      new Uint8Array(readFileSync(path)),
      teams,
    );
    games = games.concat(toGames(report, week));
    notes.push(
      `Week ${week}: ${report.totalRows} rows -> ${report.games.length} games, ` +
        `${report.duplicates.length} duplicates collapsed, ${report.skipped.length} skipped`,
    );
    for (const w of report.warnings) notes.push(`  check: ${w}`);
  }

  const out: string[] = [];
  out.push("-- ALPreps Index — initial data");
  out.push("-- Generated by scripts/make-seed-sql.ts. Do not hand-edit.");
  out.push("--");
  out.push(`-- Teams: ${teams.length}, with ${matched} preseason ratings`);
  out.push(`-- Aliases: ${Object.keys(ALIASES).length}`);
  out.push(`-- Games: ${games.length}`);
  for (const n of notes) out.push(`-- ${n}`);
  out.push("--");
  out.push("-- Safe to re-run. Existing scores, and an existing formula");
  out.push("-- config, are preserved.");
  out.push("");
  out.push("begin;");
  out.push("");

  // ---- teams -------------------------------------------------------------
  out.push("-- Teams ------------------------------------------------------");
  out.push(
    "insert into teams (name, slug, classification, region, preseason_prior, prior_source) values",
  );
  out.push(
    teams
      .map(
        (t) =>
          `  (${q(t.name)}, ${q(t.slug)}, ${q(t.classification)}, ${t.region}, ` +
          `${num(t.preseason_prior)}, ${t.prior_source ? q(t.prior_source) : "NULL"})`,
      )
      .join(",\n"),
  );
  out.push("on conflict (name) do update set");
  out.push("  slug = excluded.slug,");
  out.push("  classification = excluded.classification,");
  out.push("  region = excluded.region,");
  out.push("  preseason_prior = excluded.preseason_prior,");
  out.push("  prior_source = excluded.prior_source;");
  out.push("");

  // ---- aliases -----------------------------------------------------------
  const aliasPairs = Object.entries(ALIASES).filter(([, canonical]) =>
    teams.some((t) => t.name === canonical),
  );
  out.push("-- Schedule-PDF name aliases ---------------------------------");
  out.push("insert into team_aliases (alias, team_id, source)");
  out.push("select v.alias, t.id, 'seed'");
  out.push("from (values");
  out.push(
    aliasPairs.map(([a, c]) => `  (${q(a)}, ${q(c)})`).join(",\n"),
  );
  out.push(") as v(alias, team_name)");
  out.push("join teams t on t.name = v.team_name");
  out.push("on conflict (alias) do nothing;");
  out.push("");

  // ---- config ------------------------------------------------------------
  out.push("-- Formula config (left alone if one already exists) ----------");
  out.push(
    `insert into config (id, data) values (1, ${q(JSON.stringify(DEFAULT_CONFIG))}::jsonb)`,
  );
  out.push("on conflict (id) do nothing;");
  out.push("");

  // ---- games -------------------------------------------------------------
  if (games.length) {
    out.push("-- Schedule --------------------------------------------------");
    out.push("insert into games (t1, s1, t2, s2, week, type, round, date, status) values");
    out.push(
      games
        .map(
          (g) =>
            `  (${q(g.t1)}, NULL, ${q(g.t2)}, NULL, ${g.week}, ${q(g.type)}, ` +
            `${g.round ? q(g.round) : "NULL"}, ${g.date ? q(g.date) : "NULL"}, 'scheduled')`,
        )
        .join(",\n"),
    );
    // Never disturb a game that already carries a result.
    out.push("on conflict (t1, t2, week, type) do update set");
    out.push("  date = excluded.date");
    out.push("  where games.s1 is null and games.s2 is null;");
    out.push("");
  }

  out.push("commit;");
  out.push("");
  out.push("-- Check:");
  out.push("--   select classification, count(*) from teams group by 1 order by 1;");
  out.push("--   select count(*) from games;");
  out.push("");

  mkdirSync("supabase", { recursive: true });
  const sql = out.join("\n");
  writeFileSync("supabase/seed.sql", sql);

  console.log(`Wrote supabase/seed.sql (${(sql.length / 1024).toFixed(0)} KB)`);
  console.log(`  ${teams.length} teams, ${matched} with preseason ratings`);
  console.log(`  ${aliasPairs.length} aliases`);
  console.log(`  ${games.length} games`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
